Flask:
  SECRET_KEY: 'YF2f7Gj^z#wr'
MQTT:
  BROKER_URL: 'howest-energy-monitoring.westeurope.cloudapp.azure.com'
  BROKER_PORT: 1883
InfluxDB:
  Howest:
    URL: 'https://westeurope-1.azure.cloud2.influxdata.com'
    TOKEN: 'UHsDOThV6ppsYloBTclKuJCoGRLmjetBvRNJw8ThfkJ2kqNniqFXLJR2ToB1oLlrd7QICsT60oitttWNLx9UVA=='
    ORG: 'merijn.defoort@student.howest.be'
    BUCKET: "Transfo Zwevegem"
  Transfo:
    URL: 'http://howest-energy-monitoring.westeurope.cloudapp.azure.com:8086'
    TOKEN: 'R1y9jV0mvg4_yU-DMCtXnhrNChRsQwxib4Nj60WtWKLbKHChThCzrFFg-kmlAe-yOvKpz9YGOpYnX_Kh7xYxEQ=='
    ORG: 'Howest'
    BUCKET: 'Transfosite'
Smappee:
  Channels:
    5500031443 D: "Stopcontact16A EB1.D"
    5500033160 B: "Stopcontact16A EB1.D"
    5500033160 A: "Stopcontact16A EB1.D"
    5500033102 A: "Stopcontact 63A fuifzaal EB1"
    5500033102 B: "Stopcontact 63A fuifzaal EB1"
    5500033102 C: "Stopcontact 63A fuifzaal EB1"
    5500031425 A: "Stopcontact125A EB1.A"
    5500031425 B: "Stopcontact125A EB1.A"
    5500031425 C: "Stopcontact125A EB1.A"
    5500031443 A: "Voeding Fuifzaal EB1.I"
    5500031443 B: "Voeding Fuifzaal EB1.I"
    5500031443 C: "Voeding Fuifzaal EB1.I"
    5500033160 C: "Stopcontact32A EB1.C"
    5500033160 D: "Stopcontact32A EB1.C"
    5500033102 D: "Stopcontact32A EB1.C"
    5500031417 A: "Machinezaal EB3.A"
    5500031417 B: "Machinezaal EB3.A"
    5500031417 C: "Machinezaal EB3.A"
    5500031417 D: "Kantoren verdiep 4 EB3.B"
    5500033167 A: "Kantoren verdiep 4 EB3.B"
    5500033167 B: "Kantoren verdiep 4 EB3.B"
    5500033167 C: "Oenanthé EB3.C"
    5500033167 D: "Oenanthé EB3.C"
    5500031540 A: "Oenanthé EB3.C"
    5500031540 B: "Verdieping 5 EB3.D"
    5500031540 C: "Verdieping 5 EB3.D"
    5500031540 D: "Verdieping 5 EB3.D"
    5500033164 A: "Waterkot EB3.I"
    5500033164 B: "Waterkot EB3.I"
    5500033164 C: "Waterkot EB3.I"
    5500033164 D: "Reserve loods EB3.H"
    5500031412 A: "Reserve loods EB3.H"
    5500031412 B: "Reserve loods EB3.H"
    5500031536 A: "CE stekker fuifzaal Opbouw"
    5500031536 B: "CE stekker fuifzaal Opbouw"
    5500031536 C: "CE stekker fuifzaal Opbouw"
    5500031536 D: "Silo"
